# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "lbl-theme"
license = "MIT"
licenselink = "https://github.com/mattstratton/lbl-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/mattstratton/lbl-theme"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Matt Stratton"
  homepage = "https://www.mattstratton.com"
